Programa6_1: programa6_1.cpp PoligonoIrreg.o
	g++ programa6_1.cpp PoligonoIrreg.o Coordenada.o -o programa6_1
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c